site:
  title: DDM Documentation
  start_page: index.adoc
asciidoc:
  attributes:
    page-pagination: '@'
    favicon: ddl_favicon_black.svg
content:
  sources:
    - url: ../
      branches: [develop]
      tags: [v1.0.19, v1.0.0]
      version: true
      start_path: docs
ui:
  bundle:
    url: ./ui/ui-bundle.zip
    snapshot: true
